declare const _default: {
    new (): {
        _dat: Uint16Array;
        _set: number;
        toDefault(): void;
        clone(): any;
        patch(cfg: any, out: any): void;
        setupGL(gl: WebGLRenderingContext): void;
        fromGL(gl: WebGLRenderingContext): void;
        enableBlend(flag?: boolean): any;
        blendFunc(src: number, dst: number): any;
        blendFuncSeparate(srcRgb: number, dstRgb: number, srcAlpha: number, dstAlpha: number): any;
        blendEquation(eq: number): any;
        blendEquationSeparate(rgbEq: number, alphaEq: number): any;
        blendColor(r: number, g: number, b: number, a: number): any;
        depthFunc(func: number): any;
        enableDepthTest(flag?: boolean): any;
        depthRange(near: number, far: number): any;
        lineWidth(w: number): any;
        cullFace(mode: number): any;
        enableCullface(flag: boolean): any;
        polygonOffset(polyOffsetFactor: number, polyOffsetUnits: number): any;
        enablePolygonOffset(flag?: boolean): any;
        enableScissor(flag?: boolean): any;
        scissor(x: number, y: number, w: number, h: number): any;
        viewport(x: number, y: number, w: number, h: number): any;
        enableDither(flag?: boolean): any;
        depthMask(flag: boolean): any;
        colorMask(r: number, g: number, b: number, a: number): any;
        frontFace(dir: number): any;
        enableStencil(flag?: boolean): any;
        stencilFunc(func: number, ref: number, mask: number): any;
        stencilOp(sfail: number, dpfail: number, dppass: number): any;
        stencilMask(mask: number): any;
        stencilFuncSeparate(func: number, ref: number, mask: number, funcback: number, refback: number, maskback: number): any;
        stencilOpSeparate(sfail: number, dpfail: number, dppass: number, sfailback: number, dpfailback: number, dppassback: number): any;
        stencilMaskSeparate(mask: number, maskback: number): any;
    };
    DAT_MASKS: number[];
    encodeHalf(f32: number): number;
    decodeHalf(u16: number): number;
};
export = _default;
